apiVersion: v1
kind: Service
metadata:
    name: view
spec:
    ports:
        -   port: 80
            protocol: TCP
            targetPort: 80
    selector:
        app: view
    sessionAffinity: None
    type: LoadBalancer
status:
    loadBalancer: {}