apiVersion: v1
kind: Service
metadata:
    name: view
spec:
    type: NodePort
    ports:
        -   port: 80
            targetPort: 80
            nodePort: 32080
            protocol: TCP
    selector:
        app: view